### ISSUE TITLE
Mobile/small viewport issues 

### ISSUE THREAD

**Issue by synnovsh** [synnovsh/eit#50]
![Screenshot_20200329-111752](https://user-images.githubusercontent.com/1827289/77845552-07f68280-71b0-11ea-8475-516651e8e5c4.jpg)

Shouldn't show image preview.
Solution night be to have a generic message 

![Screenshot_20200329-112645](https://user-images.githubusercontent.com/1827289/77845606-7fc4ad00-71b0-11ea-8edd-acb93f6aa206.jpg)

Menu should have priority over arrows

**Comment by Tor-Erik-kode** [comment]
![91187590_212094546750364_7914363956058128384_n](https://user-images.githubusercontent.com/61801598/78125810-d846b500-7411-11ea-8a97-89271252da43.jpg)

**Comment by Tor-Erik-kode** [comment]
Gradient for the title on tablet.
Den mørke gradienten som skal ligge over bildet forsvinner i bunnen av bildet
